feat: add the article share
goplus/community pull request #108
Opened 2024-02-05 15:38 UTC by xhyqaq

2024-02-05 15:40 UTC, xhyqaq commented
@IRONICBo CR

2024-02-05 16:08 UTC, IRONICBo requested changes

2024-02-05 16:08 UTC, IRONICBo commented on internal/core/community.go
> +			userId = "游客"
@xhyqaq Please use english, and do not set `userId` to string.

2024-02-07 16:14 UTC, IRONICBo approved these changes
LGTM

2024-02-07 16:19 UTC, merged