chore: change yap version for support include tempalte
goplus/community pull request #109
Opened 2024-02-05 15:39 UTC by LiusCraft

https://github.com/goplus/yap/pull/49 no merge, so use: `replace github.com/goplus/yap v0.7.2 => github.com/LiusCraft/yap v0.8.2`

2024-02-05 16:07 UTC, IRONICBo requested changes

2024-02-05 16:07 UTC, IRONICBo commented on cmd/gopcomm/gop_autogen.go
> +<<<<<<< HEAD
Please update your merged code.

2024-02-06 06:27 UTC, IRONICBo commented
@Kasey0727 Please review :)

2024-02-06 08:27 UTC, Kasey0727 approved these changes
LGTM

2024-02-06 12:03 UTC, LiusCraft commented
@IRONICBo @Kasey0727 TBR

2024-02-07 01:38 UTC, IRONICBo approved these changes
LGTM

2024-02-07 01:38 UTC, merged