fix: bind account
goplus/community pull request #148
Opened 2024-02-19 12:01 UTC by LiusCraft

2024-02-19 14:16 UTC, IRONICBo requested changes

2024-02-19 14:16 UTC, IRONICBo commented on internal/core/casdoor.go
> +	return map[string]bool{
Use struct instead.

2024-02-19 14:16 UTC, IRONICBo commented on internal/core/casdoor.go
> +package core
Why not move them to `user.go`?

2024-02-19 14:16 UTC, IRONICBo commented on internal/core/casdoor.go
> +		log.Println(err)
Use xlog.

2024-02-19 14:16 UTC, IRONICBo commented on internal/core/casdoor.go
> +		log.Println(response.Msg)
Use xlog.

2024-02-19 14:16 UTC, IRONICBo commented on internal/core/casdoor_test.go
> +		t.Skip(err)
Do not skip error.

2024-02-19 14:16 UTC, IRONICBo commented on internal/core/casdoor_test.go
> +		t.Skip(err)
Do not skip them.

2024-02-20 12:47 UTC, IRONICBo commented on cmd/gopcomm/community_yap.gox
> +	println gac
Suggest to remove it.

2024-02-20 12:48 UTC, IRONICBo commented on cmd/gopcomm/community_yap.gox
> +get "/userUnlink", ctx => {
Suggest to use `/user/unlink` instead.

2024-02-20 12:49 UTC, IRONICBo commented on cmd/gopcomm/community_yap.gox
> +get "/userEdit", ctx => {
Ditto

2024-02-20 13:50 UTC, LiusCraft commented on cmd/gopcomm/community_yap.gox
> +get "/userUnlink", ctx => {
Yap now support this type of router?

2024-02-21 01:24 UTC, IRONICBo commented on cmd/gopcomm/community_yap.gox
> +get "/userEdit", ctx => {
`put /user/:id`

2024-02-21 10:54 UTC, IRONICBo approved these changes
LGTM

2024-02-21 10:54 UTC, merged