feat: support video list with duration and upload video file with duration
goplus/community pull request #179
Opened 2024-02-22 13:55 UTC by xhyqaq

2024-02-22 15:43 UTC, IRONICBo requested changes

2024-02-22 15:43 UTC, IRONICBo commented on internal/core/media.go
> +		fmt.Println(err.Error())
Do not use common println.

2024-02-25 14:09 UTC, xhyqaq commented on internal/core/media.go
> +		fmt.Println(err.Error())
> Do not use common println.

Mine, I forgot to take the test

2024-02-26 02:17 UTC, IRONICBo approved these changes
LGTM

2024-02-26 02:17 UTC, merged